# Generated by Django 5.0.2 on 2025-04-12 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AddField(
            model_name='user',
            name='commercial_registration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_nationality',
            field=models.CharField(blank=True, choices=[('OMANI', 'عماني'), ('GULF', 'خليجي'), ('INT', 'أجنبي')], max_length=5, null=True, verbose_name='جنسية الشركة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='حساب موثوق'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة المفضلة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بتنسيق:'+96812345678'", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'مالك العقار'), ('INVESTOR', 'مستثمر مؤجرة'), ('COMPANY', 'شركة مستأجرة')], max_length=10, verbose_name='نوع المستخدم'),
        ),
    ]
