# Generated by Django 5.0.2 on 2025-04-12 16:50

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['company_name'], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='investor',
            name='bank_details',
            field=models.JSONField(blank=True, help_text='تفاصيل الحساب البنكي لتحويل الأرباح', null=True, verbose_name='تفاصيل البنك'),
        ),
        migrations.AddField(
            model_name='investor',
            name='contract_duration',
            field=models.PositiveIntegerField(default=1, help_text='مدة عقد الاستثمار بالسنوات', verbose_name='مدة العقد (سنوات)'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='المبلغ الذي استثمره المستثمر', max_digits=12, verbose_name='مبلغ الاستثمار'),
        ),
        migrations.AddField(
            model_name='investor',
            name='investment_date',
            field=models.DateField(default='', help_text='تاريخ بداية الاستثمار', verbose_name='تاريخ الاستثمار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='bank_name',
            field=models.CharField(blank=True, help_text='البنك الذي يتلقى المالك مدفوعاته منه', max_length=100, null=True, verbose_name='اسم البنك'),
        ),
        migrations.AddField(
            model_name='owner',
            name='iban_number',
            field=models.CharField(blank=True, help_text='رقم الآيبان لتحويل الأرباح', max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='يجب إدخال رقم آيبان صحيح', regex='^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$')], verbose_name='رقم الآيبان'),
        ),
        migrations.AddField(
            model_name='owner',
            name='ownership_percentage',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='نسبة ملكية المالك في المبنى', max_digits=5, verbose_name='نسبة الملكية'),
        ),
        migrations.AddField(
            model_name='owner',
            name='preferred_payment_method',
            field=models.CharField(choices=[('BANK', 'تحويل بنكي'), ('CHEQUE', 'شيك'), ('CASH', 'نقدي')], default='BANK', help_text='الطريقة المفضلة لاستلام المدفوعات', max_length=20, verbose_name='طريقة الدفع المفضلة'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='authorized_person',
            field=models.CharField(default='', help_text='اسم الشخص المفوض بالتوقيع عن الشركة', max_length=100, verbose_name='الشخص المفوض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='authorized_person_id',
            field=models.CharField(default='', help_text='رقم هوية الشخص المفوض', max_length=20, verbose_name='رقم هوية المفوض'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_activity',
            field=models.CharField(default='', help_text='النشاط التجاري الرئيسي للشركة المستأجرة', max_length=100, verbose_name='نشاط الشركة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='اسم جهة الاتصال في حالات الطوارئ', max_length=100, null=True, verbose_name='جهة اتصال الطوارئ'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='insurance_expiry',
            field=models.DateField(blank=True, help_text='تاريخ انتهاء بوليصة التأمين', null=True, verbose_name='انتهاء التأمين'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='insurance_policy',
            field=models.CharField(blank=True, help_text='رقم بوليصة التأمين على المحتويات إن وجدت', max_length=50, null=True, verbose_name='بوليصة التأمين'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='مسقط', help_text='المدينة الرئيسية للشركة', max_length=50, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='شعار الشركة الرسمي', null=True, upload_to='company_logos/', verbose_name='شعار الشركة'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_name_english',
            field=models.CharField(blank=True, help_text='اسم الشركة باللغة الإنجليزية إن وجد', max_length=150, null=True, verbose_name='اسم الشركة (الإنجليزية)'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(default='OM', help_text='الدولة المسجلة فيها الشركة', max_length=2, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='user',
            name='establishment_date',
            field=models.DateField(blank=True, help_text='تاريخ تأسيس الشركة', null=True, verbose_name='تاريخ التأسيس'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='يحدد ما إذا تم التحقق من صحة المستخدم', verbose_name='حساب موثوق'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='تاريخ آخر تعديل على بيانات الحساب', verbose_name='آخر تحديث'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, help_text='الرمز البريدي للعنوان', max_length=20, null=True, verbose_name='الرمز البريدي'),
        ),
        migrations.AddField(
            model_name='user',
            name='tax_number',
            field=models.CharField(blank=True, help_text='الرقم الضريبي للشركة إن وجد', max_length=50, null=True, unique=True, verbose_name='الرقم الضريبي'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='الموقع الرسمي للشركة إن وجد', null=True, verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='investment_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='نسبة الاستثمار في الأرباح', max_digits=5, verbose_name='نسبة الاستثمار'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'INVESTOR'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='investor_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'OWNER'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tenant_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(help_text='العنوان الرسمي للشركة', verbose_name='العنوان التفصيلي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='commercial_registration',
            field=models.CharField(help_text='رقم السجل التجاري الصادر من الوزارة', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يحتوي السجل التجاري على أرقام فقط', regex='^[0-9]+$')], verbose_name='السجل التجاري'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(help_text='الاسم الرسمي للشركة كما في السجل التجاري', max_length=150, verbose_name='اسم الشركة'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='تاريخ إنشاء الحساب', verbose_name='تاريخ التسجيل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='البريد الإلكتروني الرسمي للشركة', max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='يحدد ما إذا كان يمكن للمستخدم تسجيل الدخول', verbose_name='حساب نشط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='يحدد ما إذا كان المستخدم يمكنه الوصول إلى لوحة الإدارة', verbose_name='صلاحيات موظف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'مالك المبنى'), ('INVESTOR', 'مستثمر المبنى'), ('TENANT', 'مستأجر الوحدة'), ('ADMIN', 'مدير النظام')], help_text='تحديد نوع المستخدم (مالك، مستثمر، مستأجر)', max_length=10, verbose_name='نوع المستخدم'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['company_name'], name='users_user_company_fc49fb_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['commercial_registration'], name='users_user_commerc_28cac2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_user_ty_4573bb_idx'),
        ),
    ]
