# Generated by Django 5.0.2 on 2025-04-12 10:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_commercial_registration_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'permissions': [('can_manage_properties', 'يمكنه إدارة العقارات'), ('can_view_reports', 'يمكنه عرض التقارير')], 'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمون'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='language',
            new_name='preferred_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='commercial_registration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_nationality',
        ),
        migrations.AddField(
            model_name='user',
            name='comany_license',
            field=models.FileField(blank=True, null=True, upload_to='company_licenses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])], verbose_name='رخصة الشركة'),
        ),
        migrations.AddField(
            model_name='user',
            name='commercial_reg_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_type',
            field=models.CharField(blank=True, choices=[('OM', 'عماني'), ('GCC', 'خليجي'), ('INT', 'أجنبي'), ('MIX', 'مختلط عماني واجنبي')], max_length=5, null=True, verbose_name='نوع الشركة'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='رقم الهوية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='related_accounts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='الحسابات المرتبطة'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='رمز التحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='واتساب'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='يجب أن يبدأ رقم الهاتف بــ +968 ويتبعه 8 أرقام', regex='^\\+?968\\d{8}$')], verbose_name='هاتف عماني'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('OWNER', 'مالك العقار'), ('INVESTOR', 'مستثمر مؤجرة'), ('COMPANY', 'شركة مستأجرة'), ('GOVERNMENT', 'جهة حكومية')], default='COMPANY', max_length=10, verbose_name='نوع المستخدم'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='user_avatars/', verbose_name='الصورة الشخصية')),
                ('nationality', models.CharField(blank=True, max_length=100, null=True, verbose_name='الجنسية')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='جهة اتصال طوارئ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف تعريفي',
                'verbose_name_plural': 'الملفات تعريفية',
            },
        ),
    ]
